Better UI
DCMLab/tree-annotation-code pull request #17
Opened 2019-11-15 23:11 UTC by chfin

- uses a CSS framework (pure-css)
- allows hiding IO sections (automatically on load)
- responsive
- better tree layout
  - flexible width
  - larger buttons
  - done via nested divs and CSS

2019-11-15 23:15 UTC, chfin commented
Will solve #9 and #10

2019-11-18 10:00 UTC, dharasim requested changes
Looks good! I really like using nested divs instead of node coordinates. There are just some minor things here and there. I would be good to have a quick read through the code and delete all functions that are not used anymore to keep the code clean, e.g. the recalculation of the coordinates should be obsolete now.

2019-11-18 10:00 UTC, dharasim commented on resources/public/css/style.css
> +    min-width: 60px;
```suggestion
    min-width: 10px;
```

10px are totally enough here. For long sequences like in real world examples, it is important to save as much horizontal space as possible.

2019-11-18 10:00 UTC, dharasim commented on src/tree_annotation/core.cljs
> +
can be deleted

2019-11-18 10:00 UTC, dharasim commented on src/tree_annotation/core.cljs
This function would be clearer if it would return "node selected", "node tree-selected", and "node", respectively.

2019-11-18 10:00 UTC, dharasim commented on src/tree_annotation/core.cljs
> +             ;; :style (node-style node)
Can be deleted.

2019-11-18 10:00 UTC, dharasim commented on src/tree_annotation/core.cljs
> +     {;:style style
```suggestion
```

2019-11-18 10:00 UTC, dharasim commented on src/tree_annotation/core.cljs
> +      :class (str "node" (selection-class node))
```suggestion
     {:class (selection-class node)
```

2019-11-18 10:00 UTC, dharasim commented on src/tree_annotation/core.cljs
>  ;; todo: make component structure nested
This is done now, right?

2019-11-18 10:00 UTC, dharasim commented on src/tree_annotation/core.cljs
> +   [:a {:on-click db/toggle-io! :href "javascript:void(0)"}
Please comment on what the string "javascript:void(0)" is for.

2019-11-18 10:00 UTC, dharasim commented on src/tree_annotation/core.cljs
> +        (when (identical? (.-target event) (.-body js/document))
Please comment on what this line does.

2019-11-18 10:07 UTC, chfin commented on src/tree_annotation/core.cljs
> +   [:a {:on-click db/toggle-io! :href "javascript:void(0)"}
You need a non-empty href for an `a` tag to become a link. Sometimes `#` is used, but that messes with your history, so `javascript:void(0)` seems to be the "right" solution (according to SO). I'll add a comment.

2019-11-18 10:11 UTC, chfin commented on src/tree_annotation/core.cljs
No, I don't think so. `node` and `selected`/`tree-selected` have different semantics. `node` expresses that something is a node, `*selected` marks selected nodes, so this is orthogonal. The function `selection-class` only deals with the selection status. Maybe a docstring is helpful here.

2019-11-18 10:23 UTC, chfin commented on src/tree_annotation/core.cljs
>  ;; todo: make component structure nested
What do you mean?

2019-11-18 10:59 UTC, dharasim approved these changes

2019-11-18 11:01 UTC, merged